apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canaries.k8sdeployoperator.k8s.io
spec:
  group: k8sdeployoperator.k8s.io
  version: v1
  names:
    kind: Canary
    plural: canaries
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            weight:
              type: integer
              minimum: 1
              maximum: 3