kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-operator
  namespace: kube-system
  labels:
    app: deploy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-operator
  template:
    metadata:
      labels:
        app: deploy-operator
      # annotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/path: '/stats/prometheus'
      #   prometheus.io/port: '9000'
    spec:
      serviceAccountName: deploy-operator
      containers:
      - name: k8s-deploy-operator
        image: 'iyacontrol/deploy-operator:v0.0.1'
        env:
        - name: 'CPUS'
          value: '1'
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        imagePullPolicy: Always