---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-operator
subjects:
- kind: ServiceAccount
  name: deploy-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-operator
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups: ["k8sdeployoperator.k8s.io"]
  resources: ["canaries"]
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---